# Generated by Django 5.1.4 on 2025-02-02 18:53

import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro_text", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("richtext", 0)],
                        blank=True,
                        block_lookup={0: ("wagtail.blocks.RichTextBlock", (), {})},
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "blog entry page",
                "verbose_name_plural": "blog entry pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
