# Generated by Django 5.1.4 on 2025-02-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_blogindexpage_blogpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="blog_posts_per_page",
            field=models.IntegerField(
                default=10, help_text="Specify the number of blog posts to display per page on the blog index."
            ),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="pagination_page_param",
            field=models.CharField(
                default="page", help_text="Specify the query parameter to use for pagination.", max_length=255
            ),
        ),
    ]
