name: 'Docker Build & Push'
description: 'Build and push Docker images to a registry'

inputs:
  registry-url:
    description: 'Registry URL (e.g., 10.13.13.1:5000)'
    required: true
  registry-username:
    description: 'Registry username'
    required: true
  registry-password:
    description: 'Registry password'
    required: true
  image-name:
    description: 'Image name (e.g., myimage)'
    required: true
  image-tag:
    description: 'Image tag (default: latest)'
    required: false
    default: 'latest'
  dockerfile-path:
    description: 'Path to Dockerfile (default: .)'
    required: false
    default: '.'
  build-context:
    description: 'Build context path (default: .)'
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Log in to Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry-url }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    - name: Build Docker Image
      shell: bash
      run: |
        docker build -f ${{ inputs.dockerfile-path }}/Dockerfile -t ${{ inputs.registry-url }}/${{ inputs.image-name }}:${{ inputs.image-tag }} ${{ inputs.build-context }}

    - name: Push Docker Image
      shell: bash
      run: |
        docker push ${{ inputs.registry-url }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
